type Subscription {
    messageAdded: Message
  }

  type Message {
    user: String
    message: String
  }

  type Mutation {
    addMessage(user: String, message: String): Message
  }

  type Query {
    messages: [Message]
  }